import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const disableCanvas = true;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div
          className={`absolute  ${
            disableCanvas ? " bg-black" : "pointer-events-none"
          } w-full`}
        >
          {children}
        </div>
        {!disableCanvas && (
          <canvas className="-z-10 h-screen w-screen fixed"></canvas>
        )}
      </body>
      <Script src="/scripts/fluid_cursor.js" />
      <Script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/ScrollSmoother.min.js" />
    </html>
  );
}
